theme = "awesome-identity"
baseURL = "https://www.ryan-shah.com"
title = "Ryan Shah's Website"


## Profile Configurations
[params.profile]
  portrait = "/images/portrait.png"
  firstname = "Ryan"
  lastname = "Shah"
  title = "Software Engineer"
  bio = """Current Software Engineer at [Capital One](https://www.capitalone.com/)

  3+ years experience in backend development, infastructure automation, and MVC applications.

  Graduated from the University of Kentucky in 2018 with a BS in Computer Science and Mathematics with a minor in Physics.

  Interests include automating my work-from-home life, white hat hacking/security, and learning new technologies and tools along the way.
  """
[params.contacts]
  email = "ryan@ryan-shah.com"
  github = "ryan-shah"
  facebook = "ryanshah96"
  linkedin = "ryan-shah"

[[params.actions]]
  name = "review my resume"
  url = "https://github.com/ryan-shah/Awesome-CV/raw/master/output/ryan-resume.pdf"

[params.crisp]
  websiteId = "9b56f3a7-0cc3-44e6-9cb2-f22606253673"
  # Change the chatbox color theme
  color = "red"
  # Reverse the chatbox position
  reversePosition = false
  # Hide chatbox on mobile devices
  hideOnMobile = false
  # Hide chatbox on support away
  hideOnAway = false
  # Hide chatbox on vacation
  hideVacation = false

## Footer Configurations
[params.footer]
  copyright = "© 2021 Ryan Shah. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
