theme = "awesome-identity"
baseURL = "https://www.ryan-shah.com"
title = "Awesome Identity for Hugo"


## Profile Configurations
[params.profile]
  portrait = "/images/portrait.png"
  firstname = "Ryan"
  lastname = "Shah"
  title = "Software Engineer"
  bio = """Current Software Engineer at [Lexmark International](https://www.lexmark.com/en_us.html).

  3 years experience working on multiple teams in the R&D area of the company, gaining experience in a wide array of software disciplines.

  Graduated from the University of Kentucky in 2018 with a Bachelors of Science in Computer Science and Mathematics with a minor in Pyhics.

  Interested in automating my work-from-home life and learning new technologies and tools along the way.
  """
[params.contacts]
  email = "ryan.shah96@gmail.com"
  github = "ryan-shah"
  facebook = "ryanshah96"
  linkedin = "ryan-shah"

[[params.actions]]
  name = "review my resume"
  url = "https://github.com/ryan-shah/Awesome-CV/raw/master/output/ryan-resume.pdf"

## Footer Configurations
[params.footer]
  copyright = "© 2021 Ryan Shah. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
